# Disable rules from the default enabled set
disabled_rules:
  - closure_parameter_position
  - trailing_newline
  - unneeded_break_in_switch
  - void_return
  - identifier_name

# Enable rules not from the default set
opt_in_rules:
  - closure_end_indentation
  - collection_alignment
  - empty_count
  - empty_string
  - explicit_self
  - fatal_error_message
  - file_types_order
  - first_where
  - last_where
  - force_unwrapping
  - missing_docs
  - multiline_arguments
  - operator_usage_whitespace

line_length:
  ignores_function_declarations: true
  ignores_urls: true

# Paths to ignore during linting
excluded:
  - Pods
