language: objective-c
os: osx
osx_image: xcode11.1
xcode_project: WhoIsAliveFromRickAndMorty.xcodeproj
xcode_scheme: WhoIsAliveFromRickAndMorty
xcode_destination: platform=iOS Simulator,OS=13.1,name=iPhone 11
